import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import { useState, type FormEvent } from "react";
import { BsSearch } from "react-icons/bs";
import Spinner from "../components/Spinner";
import Weather from "../components/Weather";
import type { WeatherData } from "../types/weather";

export default function Home() {
  const [city, setCity] = useState("");
  const [weather, setWeather] = useState<WeatherData | null>(null);
  const [loading, setLoading] = useState(false);
  const [errors, setErrors] = useState<string | null>(null);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

  const fetchWeather = async (e: FormEvent) => {
    e.preventDefault();
    setErrors(null);
    setLoading(true);
    try {
      const response = await axios.get<WeatherData>(url);
      setWeather(response.data);
      setCity("");
    } catch {
      setErrors("City not found. Please enter a valid city");
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return <Spinner />;
  }

  return (
    <div>
      <Head>
        <title>Weather - Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="absolute top-0 left-0 right-0 bottom-0 z-[1]  w-full max-h-full" />

      <Image
        src="https://images.unsplash.com/photo-1658302640218-f6ea33f8effa?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80"
        alt=""
        fill
      />
      <div className="z-10 absolute top-0 w-full p-2 font-bold  text-white text-center bg-slate-500">
        GET THE LOCAL WEATHER FOR ANY CITY
      </div>

      <div className="relative flex justify-between items-center max-w-[500px] w-full m-auto pt-16 px-2 lg:mt-10 text-white z-10">
        <form
          onSubmit={fetchWeather}
          className="flex justify-between items-center w-full m-auto  p-3 bg-transparent border border-white border-4  text-white rounded-2xl"
        >
          <div>
            <input
              value={city}
              onChange={(e) => setCity(e.target.value)}
              className="bg-transparent border-none text-white font-bold focus:outline-none text-2xl"
              type="text"
              placeholder="Enter a city name"
            />
            {errors && <div>{errors}</div>}
          </div>

          <button type="submit" aria-label="Search">
            <BsSearch size={22} />
          </button>
        </form>
      </div>

      {weather?.main && <Weather data={weather} />}
    </div>
  );
}
